### ISSUE TITLE
Line breaks in conditional sections being ignored

### ISSUE THREAD

**Issue by marcauberer** [compose-generator/ccom#99]
When having line breaks within one conditional section, these are removed after compiling. That causes potential parsing errors later for CG.

Example:
```yaml
image: adguard/adguardhome:v${{ADGUARD_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-frontend-adguard
restart: always
volumes:
  - ${{VOLUME_ADGUARD_DATA}}:/opt/adguardhome/work
  - ${{VOLUME_ADGUARD_CONFIG}}:/opt/adguardhome/conf
ports:
  - 53:53/tcp
  - 53:53/udp
#? if var.ADGUARD_ENABLE_DHCP == "true" {
#   - 67:67/udp
#   - 68:68/tcp
#   - 68:68/udp
#? }
#? if var.ADGUARD_ENABLE_UI == "true" {
#   - 80:80/tcp
#   - 443:443/tcp
#   - 443:443/udp
#   - 3000:3000/tcp
#? }
#? if var.ADGUARD_ENABLE_DOT == "true" {
#   - 853:853/tcp
#? }
#? if var.ADGUARD_ENABLE_DOQ == "true" {
#   - 784:784/udp
#   - 853:853/udp
#   - 8853:8853/udp
#? }
#? if var.ADGUARD_ENABLE_DNS_CRYPT == "true" {
#   - 5443:5443/tcp
#   - 5443:5443/udp
#? }
```

The log message from CG is:
```
ERROR: 2021/11/01 11:20:59.593752 load.go:170: Unable to load 'frontend-adguard-home': 1 error(s) decoding:

* error decoding 'Ports': Invalid ip address 53:53/udp
- 80:80/tcp - 443:443/tcp - 443: address 53:53/udp
- 80:80/tcp - 443:443/tcp - 443:: too many colons in address
```
